name: analog_photography_db
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/databases/cameras_catalogue.db
    - assets/databases/lenses_catalogue.db
    - assets/databases/films_catalogue.db
    - assets/databases/flashes_catalogue.db
    - assets/databases/exposure_meters_catalogue.db
    - assets/databases/film_scanners_catalogue.db
    - assets/databases/processors_catalogue.db
    - assets/images/cameras/agfa/
    - assets/images/cameras/canon/
    - assets/images/cameras/nikon/
    - assets/images/cameras/olympus/
    - assets/images/films/tasma/
    - assets/images/flashes/canon/
    - assets/images/lenses/asahi_pentax/
    - assets/images/meters/minolta/
    - assets/images/scanners/minolta/
    - assets/images/processors/jobo/



